### ISSUE TITLE
Define specs for GIS features

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#105]
Scheduled **"Signs Asset and Location Schema discussion** for 7/30/19 

Attendees: Diana, Jaime and Christina

Follow-up: Diana and John had discussion about proposed features and process

**Comment by dianamartin** [comment]
Working on this: 

Features for ArcGIS Online: 
- [ ] `Signs Work Spec Asset`: will use X, Y information from `sign_locations` object table in Knack and include the fields from the `spec_asset` object table in Knack. Will include `Work Order ID`. 

_Data from here will be pulling from data residing in Knack_

Features for GISMaint1
- [ ] `Locations_asset`: Locations that have been QA'd by GIS staff member
- [ ] `Signs_assets`: the asset points which include the sign types, condition, direction, installation date
