### ISSUE TITLE
7/24 - Revoke user access to Signs and Markings work orders in Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#106]
## Modify Page Logins

**Work Orders Markings Login**
- [x] Remove `Viewer`

**New Work Orders (Signs & Markings) Login**
- [x] Remove `Viewer`

**Jobs (Signs & Markings) Login**
- [x] Remove `Viewer`

**Specifications (Signs & Markings) Login**
- [x] Remove `Supervisor`

**Requester (Signs & Markings) Login**
- [x] Remove `Viewer`
- [x] Remove `Account Administrator`
- [x] Remove `Supervisor`
- [x] Remove `Technician`

**Comment by dianamartin** [comment]
User roles have been revoked for Signs and Markings module in Data Tracker, as of 7/24/19 11:46 pm.
