### ISSUE TITLE
7/24 - Delete test records from Signs and Markings Work Order app

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#107]

**Comment by johnclary** [comment]
Objects to truncate:
- `work_orders_signs`
- `work_orders_markings`
- `work_orders_signs_markings_attachments (map to signs)`
- `work_orders_signs_markings_attachments (map to markings)`
- `work_orders_markings_jobs`
- `inventory_transactions`

**Comment by johnclary** [comment]
Donezo.
