### ISSUE TITLE
Attachments JS and CSS

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#114]
The attachments JS and CSS need to be added to the application. 

Right now you see the whole file name rather than the attachment type
![image](https://user-images.githubusercontent.com/21112975/61426415-f26e5080-a8df-11e9-9801-aa1997fe99c8.png)

Should look like this:
![image](https://user-images.githubusercontent.com/21112975/61426372-d1a5fb00-a8df-11e9-9bc2-41086fe916ca.png)

@johnclary Would you be able to do this?

**Comment by dianamartin** [comment]
@mateoclarke 

## Signs Work Order Table 
`scene_1027/views/view_2565`

## Signs Work Order Details>Attachments Table 
`scene_1028/views/view_2677`

**Comment by mateoclarke** [comment]
> Markings: https://atd.knack.com/signs-markings#work-orders-markings/markings/view-work-orders-marking-details/5d13bb4cd3186524eaf1d47e/
> 
> Signs: https://atd.knack.com/signs-markings#work-order-signs/view-work-orders-details-sign/5d323d4335c4820010d126f2/
> 
> Data Tracker Production:
> Markings: https://transportation.austintexas.io/data-tracker/#home/work-orders-markings/markings/view-work-orders-marking-details/5cb7384fafac831792b6cb52/
