### ISSUE TITLE
Delete "Markings/Signs" toggle and move tables to "Signs & Markings | Work Orders" page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#116]
https://builder.knack.com/atd/21-may-2019-test-signs-migration-atd-data-tracker#pages/scene_709

- [ ] Moved `work_orders_markings` table from "Markings" to "Signs & Markings | Work Orders" page
- [ ] Moved `Menu | Admin` from "Markings" to "Signs & Markings | Work Orders" page

**Comment by dianamartin** [comment]
Tried to move it to `Signs & Markings | Work Order` page but there's something blocking the `work_orders_markings` table from appearing.

Will probably have to rebuild these pages..
![image](https://user-images.githubusercontent.com/21112975/61475652-e79fd400-a950-11e9-8ae3-f75914d8ffc5.png)

**Comment by dianamartin** [comment]
John is troubleshooting, looking at the passthrough table in Markings

**Comment by johnclary** [comment]
OK, i tried messing with the passthrough in the migration test app. I did two things: first, I just switched the menu settings from tabs to buttons. That fixes it from a UI perspective. After than, I deleted the passthrough table, and that moved the work order details from the passthrough table to below the work order search. that all seems fine., but a little scary. I would say, for now, let's just change the menu settings from tabs to buttons. then we will look at deleting the passthrough after we go-live and can test in a brand new test environment. what do you think?
