### ISSUE TITLE
Request Cancellation field not showing up on Markings Attachments table

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#144]
## Request Cancellation - Display Rules (Signs Attachment table on Work Order Details)
`Attachment Status` is - Cancelled
Hide Value

`WORK_ORDER_STATUS_SIGNS` is - NEED TO BE ISSUED
Hide Value

`WORK_ORDER_STATUS_SIGNS` is - CLOSED
Hide Value

`WORK_ORDER_STATUS_SIGNS` is - FINAL REVIEW
Hide Value

`WORK_ORDER_STATUS_SIGNS` is - CANCELLED
Hide Value

## Request Cancellation - Display Rules (Markings Attachment table on Work Order Details)
Same Display Rules

**Comment by dianamartin** [comment]
I was troubleshooting this on 7/24. I believe it is working correctly. Will document the Display Rules.
