### ISSUE TITLE
Increase "Back to View Work Order Details" font, size, visibility

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#150]
As a technician who is on the Location Details page. When they get done adding assets, they don't know to go back to the Work Order Details page. The button is currently small. It's below the Asset Form. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/fd18c88d-6495-4521-be50-9855c6482eaa)

https://atd.knack.com/24-july-2019--test-signs-and-markings-operations#my-work-orders/view-work-orders-details-sign/5d39d5bfbf7f32001058dd7a/view-work-order-signs-location-details
/5d39f05e3b39c70010b72cc1/

**Comment by amenity** [comment]
@dianamartin close once you've verified it's working in prod
