### ISSUE TITLE
Embed New Markings Calculator

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#161]
Once pull request has been reviewed and approved, will embed new iframes into [`Reference: Calculator` page](https://builder.knack.com/atd/signs-markings#pages/scene_879/views/view_2267) on Signs and Markings Operations Application.

**Comment by dianamartin** [comment]
Waiting on Tyler's PR to be reviewed and merged

Slack convo:
>**Tyler Whitson Jul 29th at 2:21 PM**
Once Mateo has reviewed my PR it will be incorporated into the main site and then we can get the final link to embed into the iFrame

**Comment by mateoclarke** [comment]
I've reviewed the code on 7/30 and had some feedback:
https://github.com/cityofaustin/transportation.austintexas.io/pull/306

Also seems like the plan should be for the code to live in this repo, `atd-knack-signs-markings` instead of `transportation.austintexas.io` where it live currently.

@tcwcodes, can you port the code over here in a new folder on root called `js-markings-calculator`? I'm worried this might take some webpack setup and might conflict with our geospatial-ui React app currently in the folder `src` so we might need to talk about how to do this IRL.

**Comment by dianamartin** [comment]
OLD EMBED CODE

<h1>Thermoplastic - extruded machine</h1>
<h2>60 mils thick (maintenance)</h2>
<iframe src="https://jscalc.io/embed/VOFQTyy7dTOmQXQg" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)" width="675" height="300" frameborder="0">
</iframe>
<h2>90 mils thick (maintenance)</h2>
<iframe src="https://jscalc.io/embed/PbbS6EU1dydbdRNR" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)" width="675" height="300" frameborder="0">
</iframe>
<h2>Beads - for extruded machine</h2>
<iframe src="https://jscalc.io/embed/OPgr9pqi6uMh8VKb" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)" width="675" height="300" frameborder="0">
</iframe>
<h2>Thermoplastic: Primer (sealant) - for extruded machine</h2>
<iframe src="https://jscalc.io/embed/BSqHZerhWb8z9DIT" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)" width="675" height="300" frameborder="0">
</iframe>
<h1>Paint</h1>
<h2>Gallons Paint Used</h2>
<iframe src="https://jscalc.io/embed/jVLwuA1lc84oxujt" width="675" height="300" frameborder="0" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)">
</iframe>
<h2>Beads (Pounds of beads)</h2>
<iframe src="https://jscalc.io/embed/lX3WsxkijPCCiG3w" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)" width="675" height="300" frameborder="0">
</iframe>
<h1>Bituminous Adhesive</h1>
<h2>4" RPMS</h2>
<iframe src="https://jscalc.io/embed/TaHPzOSpFaCMFH9C" marginheight="0" marginwidth="0" style="border: 1px solid rgba(0,0,0,0.12)" width="675" height="300" frameborder="0">
</iframe>

**Comment by dianamartin** [comment]
I removed the code in the Rich Text box

**Comment by dianamartin** [comment]
Tested on desktop and tablet. Tyler fixed it so that the calculator would be visible on a tablet.
