### ISSUE TITLE
Implement using @ in intersection geocoding in address bar in iFrame map

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-knack-signs-markings#162]
- [x] Check if geocoding is currently using this option
- [ ] Implement to improve user search for street intersections

Link from Sergio https://developer.here.com/api-explorer/rest/geocoder/latitude-longitude-intersection

**Comment by mddilley** [comment]
The Knack map address search feature currently uses Mapbox's Geocoding API which does not handle intersections well. 

Using the Here Geocoder API for [street intersections](https://developer.here.com/api-explorer/rest/geocoder/latitude-longitude-intersection) could improve this feature. Maybe adding the ability to toggle between address and intersection search (with intersection as default)? Or maybe the address search is replaced by the option to search by intersection?

I tested some Austin intersections in the link above (especially some with multiple names - Koenig/2222, Ed Bluestein/183), and it worked well. TX-71/Ben White/US-290 didn't work so well with Congress (it liked Ben White for that search). 

@dianamartin @mateoclarke What do y'all think? Trying to figure out if this change is useful in the long run and will also help with the short term issue of geolocation not performing well on the Lenovo tablets.

**Comment by dianamartin** [comment]
@mddilley @mateoclarke I like the idea of having a choice to search by intersection and or specific address on the map. I think this particular feature would be helpful it it's not a huge level of effort.

**Comment by johnclary** [comment]
I definitely think we should switch to a geocoder that supports intersections. not sure if a toggle is any better than just hitting the @ sign when typing. although it would be ideal to have autocomplete when searching by intersection. also, fwiw, i'm hoping there's much less manual entry once we move the techs to location-enabled tablets.
