### ISSUE TITLE
Discuss metrics/measures to include in Signs and Markings case study

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#178]
Now that we've completed our Maximo migration, I'd like to document the benefits of our Knack-based app versus Maximo. Some metrics that come to mind:

- ease of use technicians: how much time does it take to complete a work order in Knack vs Maximo?
- ease of use for requesters: how much time does it take to request a work order in Knack vs Maximo?
- data quality: can we compare the data we're getting today vs what we were getting in Maximo? I'm specifically thinking about geospatial data here.
- training: is it easier to on-board new users in the new system?
-  cost (licensing): how much are we saving in licensing fees? Remember that we were also considering moving the Markings staff into the Maximo system, so we should factor in that cost as well.
- cost (hardware): how much are saving in hardware fees by moving from Lenovo to Android tablets?

What am I missing?

@dianamartin do you think we could get some screenshots and do some timed tests on the Maximo test system? Or is it too late?

**Comment by dianamartin** [comment]
- ease of use technicians: how much time does it take to complete a work order in Knack vs Maximo?
- ease of use for requesters: how much time does it take to request a work order in Knack vs Maximo?
>Requests were never in Maximo. This is the process that I moved from spreadsheet to SharePoint (2015-2018) to Knack (2018/2019). We'd already optimized this process since 2018. 
- data quality: can we compare the data we're getting today vs what we were getting in Maximo? I'm specifically thinking about geospatial data here.
>We can't compare at this point since don't have the spatial data created yet
We can compare the approach of collecting the spatial data. We're using more approximate locations versus having one person add a location in Maximo based on a work order. We will be doing this too, but we will also have the techncian's location they captured. 
- training: is it easier to on-board new users in the new system?
>Training in Maximo 
- cost (licensing): how much are we saving in licensing fees? Remember that we were also considering moving the Markings staff into the Maximo system, so we should factor in that cost as well.
- cost (hardware): how much are saving in hardware fees by moving from Lenovo to Android tablets?

**Comment by johnclary** [comment]
Thanks @dianamartin moving this discussion to a [doc](https://docs.google.com/document/d/1Alhthb16-YO9EdWeoX04t0nqwWGYPmyh8_kKToV5I-A/edit)
