### ISSUE TITLE
Get metrics & screenshots of Maximo work order process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#181]
- Time a technician creating and submitting a maintenance ticket in Knack and in Maximo
- Screenshots of both UIs

Also time spatial entry.

**Comment by dianamartin** [comment]
Maximo screen shot located here: `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\AMD_DATA_TRACKER\SIGNS\Maximo_Knack_screen_shots`

**Comment by amenity** [comment]
Added to the Drive folder with the case study doc: https://drive.google.com/open?id=1gUjDrU4H7d_D7xYKK8avTBkTQG0vRUr4

**Comment by dianamartin** [comment]
@amenity I'm working on getting the Knack screen shots right now

**Comment by dianamartin** [comment]
Knack screen shot folder located here: `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\AMD_DATA_TRACKER\SIGNS\screen_shots_Knack_work_orders`. Still not done, I think i'll work on finishing it next week.

**Comment by dianamartin** [comment]
Added more Knack screen shots
