### ISSUE TITLE
Set SR Due Date from Flex Note Value

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#184]
We need to set the service request due date for all SRs so that we can create an "Aging Report" for staff to review. This information is stored in a related flex note.

We already have a script (`sr_due_date.py`) that does for AMD service requests in the Data Tracker. It needs to be extended for this app.

**Comment by dianamartin** [comment]
Email reference from John
>we're assigning the due date via script, which pulls it from the related flex note. The script runs every morning.

>We can delete the AGE_DAYS column, we ended up not needing it. The aging report just sorts by oldest to newest.

Here's the script:
https://github.com/cityofaustin/atd-data-publishing/blob/master/transportation-data-publishing/data_tracker/sr_due_date.py

**Comment by johnclary** [comment]
@dianamartin this has been deployed in production. Signs SR due dates are now being updated every morning.
