### ISSUE TITLE
BUG: Flex Notes not showing up when notes exist in 311 system

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#192]
Christina Tremel 
SMB

Said that when helping Mr. Lee, he had a work order generated from a CSR but no Flex Notes showed up. 

## SR # 19-00291623
When I reviewed it in the 311 system, the notes said the source was "phone", but the agent notes says it came from the mobile app.
![image](https://user-images.githubusercontent.com/21112975/62571007-dfeb9500-b855-11e9-8b3c-b7bcc1a20378.png)

Only has one flex note in tracker, but 6 flex notes filled out in 311 system
![image](https://user-images.githubusercontent.com/21112975/62571042-f7c31900-b855-11e9-8322-6993289ddd65.png)

Flex Notes in back end show 11 records, however they're not populated like in the system
![image](https://user-images.githubusercontent.com/21112975/62571099-26d98a80-b856-11e9-9c12-f916f381ea87.png)

**Comment by johnclary** [comment]
very strange. i wonder if 311 responder populated the flex notes some time after they created the SR. this was cause the SR flex notes initially to be published as empty. as i understand the way the integration, updates to flex notes are not published.

**Comment by johnclary** [comment]
my gut says that we should icebox or close this for now and revisit if we see it again.

**Comment by johnclary** [comment]
OK, i'm seeing lots of SRs without flex notes (Filter `csr_issues` with `COUNT_FLEX_NOTES` is `0`). I don't see any pattern to why some are missing flex notes. Need to investigate with CTM/ESB support.

**Comment by johnclary** [comment]
This was found to be an integration issue with the ESB. CTM confirmed it's been resolved.
