### ISSUE TITLE
Determine optimizations needed for Signs Work Orders 8" Tablet

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#200]
Let's review all views + forms and see if we can optimize them for use on a small screen. I'm mostly thinking about removing unneeded columns.

@dianamartin would you schedule some time to do this with the SMB staff? Please include Surbhi. I think this would be a good exercise for her. Maybe the week of the 19th?

**Comment by dianamartin** [comment]
@johnclary i'm looking at everyone's schedules and it looks like it's not a good week, following week?

**Comment by johnclary** [comment]
@dianamartin sure!

**Comment by dianamartin** [comment]
Scheduled for 8/26 @ 1pm.

**Comment by dianamartin** [comment]
Issues were created to address some of these enhancement requests. 
#207 - Location button disappears if you add comment before hand
#208 - Increase form submit buttons that are being viewed on tablet
#209 - Hide Lat/Long fields
#210 - Increase size of field headings and field inputs
#211 - Hide fields for technician users
#212 - Hide fields based on technician role
#213 - Hide "back to work orders | assigned" bread crumb, add back to top button
#214 - Increase default menu button size
#215 - Increase form submit button size
#216 - Hide lat/long fields
#217 -

**Comment by amenity** [comment]
Optimizations will be implemented in #228.
