### ISSUE TITLE
Increase Form Submit Button Sizes for Mobile Devices

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#208]
After testing on the 8" tablets, we need to increase the form submit button sizing for mobile users.

Here's the `button` element of concern. We will need to isolate this change to `type="submit"`:
```
<button class="kn-button is-primary" type="submit">
      Submit
    </button>
```

Ideally, the button would be at least twice the current height, with text size increased as well, and full-width.

**Comment by johnclary** [comment]
@mateoclarke @mddilley can we get this done during the current sprint?

**Comment by dianamartin** [comment]
## Check these locations for the submit buttons

### [Attachment form](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5d39f42940c00f24eaf9e05a/attachment-tech/5d39f42940c00f24eaf9e05a/)

### [Comment form](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5d39f42940c00f24eaf9e05a/comment-tech/5d39f42940c00f24eaf9e05a/)

### [Time](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5d39f42940c00f24eaf9e05a/)
_scroll to the bottom of the page_

### [Materials](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5d39f42940c00f24eaf9e05a/)
 _scroll to the bottom of the page_
