### ISSUE TITLE
Signs Work Orders: Hide Lat/Lon Fields

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#209]
There's not much screen real estate when viewing signs work orders on a tablet. Hide the lat/lon fields from the embedded map on the Sign Work Order Details. ![Screen Shot 2019-08-28 at 10.29.05 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/ecad3d1c-6277-4d4a-84f8-866e6cfc5b73)

- [x] Hide the `Latitude` and `Longitude` fields on the map
- [x] Make the `Add Location` button larger` #208

**Comment by johnclary** [comment]
@mateoclarke @mddilley can we get this done during the current sprint?

**Comment by mateoclarke** [comment]
Yup, we'll knock it out

**Comment by mddilley** [comment]
Making map submit button larger addressed in PR #215
