### ISSUE TITLE
Signs Work Order Details: Hide Fields for Technician Users

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#211]
For technician users only, hide:
- Printed Date (`field_3252`)
- Created Date (`field_3203`)
- Modified Date (`field_3206`)
- Modified By (`field_3283`)
- Work Type (`field_3215`)
- Work Order ID (`field_3214`)

View: `view_1885`

![image](https://user-images.githubusercontent.com/21112975/63951586-a3b9e780-ca43-11e9-8cfa-e3987e863a05.png)

**Comment by johnclary** [comment]
We did this for v1 of the DTS service request form. I'll take care of this one.

**Comment by johnclary** [comment]
Merged to master and ready to deploy. Holding off to deploy with other pending PRs.

**Comment by dianamartin** [comment]
@johnclary Did we do this for the Markings Job details too?

**Comment by johnclary** [comment]
@dianamartin no. should we do it to the same set of fields?

**Comment by dianamartin** [comment]
@johnclary I think so, just so that the SMB staff can look it over and decide if they need other fields or they should be the same. 

I'm getting them set up next week on a few tablets so they can test.
