### ISSUE TITLE
Update "Job Status" to "On Hold" when Parent WO is "On Hold" with no attachment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#220]
Christina Tremel
SMB

Emailed about
>On the “unstriped streets” report was there were streets I knew were on hold because we were waiting for plans and when I saw on my report that the jobs were in a “Need to be Issued” status I knew something was off. 

John said
>I don't see that we have any app logic that will set a job to "On Hold" if plans are missing

**Comment by dianamartin** [comment]
- [x] Test on the `24 JULY 2019 | TEST Environment`
- [ ] Add new conditional rule to `Job Status` 
WORK ORDER STATUS - contains 'HOLD`
custom value - HOLD

- [x] Create new markings work order

**Comment by dianamartin** [comment]
Talked to John and had him review the job conditional rules
### Old "On Hold" rule on the `WORK ORDER STATUS` on `work orders markings` object table. 
HOLD OTHER - is YES
CANCEL WORK ORDER - is NO
set to custom value - ON HOLD

### Old "On Hold" rule on the `JOB STATUS`, `work orders markings jobs` object table. 
HOLD WORK ORDER - is 1
COMPLETE WORK ORDER - is not - 1
CANCEL WORK ORDER - is - NO
set to custom value - HOLD

### New "On Hold" rule - replace the old one
WORK ORDER STATUS - contains ON HOLD
COMPLETE WORK ORDER - is not 1
CANCEL WORK ORDER - is No
set to custom value - HOLD

**Comment by dianamartin** [comment]
Need to test more
- [x] Created New Markings Work Order
- [ ] Add Job to existing marking work order
- [ ] Add Plans
- [ ] Add Regulation
- [ ] Put work order on hold
- [ ] Remove hold 
- [ ] Issue work order make sure status progression still works

**Comment by dianamartin** [comment]
Hadn't been able to test due to working on the TDSD application and Inventory. Will move to Sprint 8, hopefully be able to test this.

**Comment by johnclary** [comment]
@dianamartin re-test this and let me know if you need help

**Comment by dianamartin** [comment]
realizing i have to rebuild this on the new test app `18-nov-2019--test-signs-and-markings-operations`. yikes..

**Comment by dianamartin** [comment]
Scenario: 

`Viewer` enters new markings work order, the status is `On Hold` (automatically when the work order hold reason is in `Waiting for Plans'. 

The jobs status are in `Need To Be Issued`. 

#### Goal
If work order is `On Hold`, the job status should be `On Hold`.

**Comment by dianamartin** [comment]
Looking at `work_orders markings_jobs`, `JOB STATUS` to review conditional rules.

**Comment by dianamartin** [comment]
#### New "On Hold" rule - replace the old one

ISSUE WORK ORDER - is not - 1
HOLD WORK ORDER - lower than - 1
COMPLETE WORK ORDER - is lower than - 1
CANCEL WORK ORDER - is No
WORK ORDER STATUS - contains ON HOLD
set to custom value - HOLD

#### Testing Scenarios
- [x] Created New Markngs Work Order
>the jobs on the work order were in a `HOLD` status
- [x] Add Job to existing marking work order
>Added a new `Long Line` job and it went into a `HOLD` status immediately
- [x] Add Plans
>Added .pdf, and work order and jobs all went into `Need to Be Issued` status
- [ ] Add Regulation
>tried to do this, but forgot that Markings Work Order don't have "regulations" on them, only Signs. 
- [x] Put work order on hold
>work order needed to have page refresh, but work order and jobs went to `HOLD` status.
- [x] Remove hold 
>work order needed to have page refresh, but work order and jobs went to `Need to Be Issued` status.
- [x] Issue work order make sure status progression still works
> work order and jobs all went into `ISSUED` status

**Comment by dianamartin** [comment]
Need to have user test it also, then I can update the PROD environment.

**Comment by dianamartin** [comment]
Sat with Christina and showed her the rule in Test. We went through scenarios and she's happy with it. Will update to PRODUCTION.

**Comment by dianamartin** [comment]
- [x] Updated in PROD
- [x] Created a new marking work order
- [x] Saw that it created new jobs in `HOLD` status
