### ISSUE TITLE
Work History Report for permitting

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#234]
See original request [here](https://github.com/cityofaustin/atd-knack-data-tracker/issues/221#issue-501149927). 
Requested by: Kati A
SMB

>In coordination with ROW to get our Secondary Permit and MOU, it has been determined that we need to produce a weekly report of all of the locations we went to that week to attached to the permit in AMANDA.

>It will need to include things like date, location, type of work, and description of work. This will be needed for both signs and markings.

>I wanted to send this out to get it on everyone’s minds so we can start brainstorming how to get this information from Data Tracker in the most efficient way. 

>The timeline for the MOU being signed and us receiving the permit is probably a few weeks out but once the permit is live, they will be expecting these weekly reports to be attached to the permit.

**Comment by dianamartin** [comment]
I said
>I believe you can pull this information already in the “Advanced Search” page for both Signs and Markings. 

I did a filter of “Completed Date” is during the previous 1 week. It brought back 124 records, which is exportable and includes the location.
•	Filtered records

Includes fields:
•	Work Type – Type of Work
•	Work Order ID
•	Requester Work Order ID
•	Regulation #
•	311 CSR #
•	Status
•	Location - Location
•	Requester
•	Instructions –Description of work
•	Work Area
•	Coordination
•	Created - Date
•	Closed 
•	Created By

Kati replied
>Yeah, it gets a bit tricky with trying to ensure we capture all locations they performed work at, not just the jobs or work orders that were completed. Many projects last multiple days so we need a way to tell if work was put on a ticket on any day during that past week.

Christina was thinking if we would pull the information off of all tickets that have a labor date during the last week? This should be the date they were out in the field but I’m not sure if we have a way to pull a report based on this field.
![image](https://user-images.githubusercontent.com/21112975/64641299-7ec55d00-d3d1-11e9-9c00-ddb81b3e1482.png)

I replied
>We currently don’t have a report to pull the labor records by date, but that can be created.

**Comment by dianamartin** [comment]
Reference this [issue #221](https://github.com/cityofaustin/atd-knack-data-tracker/issues/221)

Create Search Page for - report based on `Time log` object table
Fields to search by and show
- [ ] date
- [ ] work type (signs or markings), 
- [ ] work group (SLN, LLN, etc.), 
- [ ] work order ID, 
- [ ] location, and 
- [ ] instructions.

**Comment by TracyLinder** [comment]
@dianamartin Can you assign somebody to this card, and move it to the correct pipeline please?

**Comment by SurbhiBakshi** [comment]
thanks @dianamartin for  your help!

**Comment by SurbhiBakshi** [comment]
@amenity as per @johnclary, adding a text formula to pull ATD Work Order ID from Signs and Markings each and then a conditional field to pull both work orders in one field  based on the source, may help enhance the resolution to this issue. Will try this approach later.

**Comment by amenity** [comment]
Thanks, @SurbhiBakshi - made issue #258 to capture that further work.
