### ISSUE TITLE
BUG: Markings GIS QA page does not re-direct to COACD.org login

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-knack-signs-markings#242]
**Describe the bug**
When logging in to Markings GIS QA page https://atd.knack.com/signs-markings#gis-qa/ the user is not re-directed to COACD.org to log in and is instead asked to login with their knack account.

**To Reproduce**
1. Go to https://atd.knack.com/signs-markings#gis-qa/ 
2. See error

**Expected behavior**
An option to log-in with COACD.org is available on this page.
This option is only available through https://atd.knack.com/signs-markings#home/ 

**Screenshots**
Error on GIS QA page:

![markings-gis-qa-non-coacdorg](https://user-images.githubusercontent.com/42655533/64889610-59378e00-d633-11e9-86f8-b6bb16061133.PNG)

Expected behavior on GIS QA page:
![markings-home-coacdorg](https://user-images.githubusercontent.com/42655533/64889629-5b015180-d633-11e9-8302-bbc01c3c9aed.PNG)

**Additional context**

**Comment by johnclary** [comment]
@SurbhiBakshi can you confirm if this has been resolved?

**Comment by SurbhiBakshi** [comment]
@johnclary I shared the app with myself and tried to log in (both in Chrome and Firefox). I can get to the main page, but not the QA site, this is what I see - 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/c9e925f2-a6a8-4086-98c5-fbf936d2195a)

**Comment by SurbhiBakshi** [comment]
@johnclary -  this is resolved now, I thought that the Grant User Role needed to be changed when it was the User Roles. @dianamartin helped me with that, and now I get redirected to the COACD login. @alan-deanda will you please test to see if you can sign in as well?

**Comment by alan-deanda** [comment]
@johnclary  @SurbhiBakshi  the issue has been resolved, I was able to log in with my COACD login from the GIS QA page on Firefox and Chrome.
