### ISSUE TITLE
Delete "csr_flex_notes" from Signs and Markings - Oct 2019

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-knack-signs-markings#256]
Received automated reminder to delete flex notes in Data Tracker PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
ISSUE_STATUS_CODE contains closed
CREATED_DATE is before 08/31/19

Total Records: 24,855
To Delete: 6,054 (number of records from running the query)
New Total: 18,801

Run Batch Delete
Same query
Filter:
ISSUE_STATUS_CODE contains closed
CREATED_DATE is before 08/31/19

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/3f0fef6f-47a5-4747-9704-9e23960ced0f)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5121cfc6-cf81-46dd-8ceb-4bb98c378d9a)

**Comment by SurbhiBakshi** [comment]
as per @johnclary , may be a bug, try again tomorrow or open a Knack ticket.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a05c0bba-0112-4060-bf99-944df6983f66)

tried again on 11/04/2019,  still can't get a batch delete to delete more than 100 records.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/60c5c8b5-68b9-45a4-84a2-2beb3d3af3e6)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b456d301-3bd7-4b77-a08a-4101b6dc65eb)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/c168c359-0d0a-43ba-96b0-c1ad7c6518b8)

**Comment by SurbhiBakshi** [comment]
@amenity , looks like this may be a bug. Have messaged Knack about this unexpected behavior today morning, yet to hear back. Have taken screenshots of steps from the process.

**Comment by johnclary** [comment]
@SurbhiBakshi you're all clear to try this again. let us know if the server migration resolved the issue.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/77f29c73-25ae-4b18-bf56-2e27f03bc902)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6c647f3c-6565-4fef-a0a2-5d6470c8d7b0)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/940dd66a-1081-43fa-b9bb-4ab56aed1d62)

**Comment by SurbhiBakshi** [comment]
@johnclary @dianamartin the migration fixed the Batch Delete bug!
