### ISSUE TITLE
View all "Final Review/Closed" Markings work orders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#257]
**Request**
Build a new table on the Markings Data Tracker page that shows work orders in "Final Review" / "Closed", and also provides completed dates and segment IDs associated. We would like to do this so we can easily update our atd_maintained_streets dataset with long line completed dates weekly.

**Outcome**
Our team will be able to update the atd_maintained_streets layer efficiently by simply using the segment IDs and will also have a back up reporting method if the markings work order / markings job layers on AGOL have issues (we experienced that this year!). This will also improve long line work planning each fiscal year. 

We currently have to have to manually search the system of all long line jobs within a date range and update with completed dates. This is a much more time consuming process!

**Details**
On this table, we would just like to see the ATD work order ID, location, completed date, work group, and segment IDs. We also want this table to be filtered and only show long line work that is in the "Final Review" or "Closed".

**Timeline**
There isn't a specific deadline I'm looking at, but if I could have this enhancement completed by December 1st that would ensure that reporting moving into this fiscal year will be improved and I won't have the issues I had last year. 

@dianamartin has confirmed that we have all the fields she needs, we just need to build out a table for them to view and pop it in their reports page. 

---
Request ID: DTS19-100300
Requested by: Christina T.

**Comment by amenity** [comment]
@amenity - coordinate with Susanne and Christina to see what they need - maybe they can reference the AGOL markings work order layers and do a spatial join with ATD Maintain Streets.

**Comment by dianamartin** [comment]
Talked to Christina and we build out the table that Susanne needs to be able to update the ATD Maintained Streets this morning.
