### ISSUE TITLE
Feature: Close Job/WO, prompts to close SR automatically (WO/JOB Details)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#266]
**Page:** 
- [ ] Markings Service Request page
- [ ] Service Request Details page
- [x] Work Order/Job Details page
- [ ] Job Details page

**Comment by dianamartin** [comment]
## Add Record Rules

![image](https://user-images.githubusercontent.com/21112975/70646848-600f7600-1c0d-11ea-8377-c28787d44148.png)

**Comment by dianamartin** [comment]
This has been added to PROD

**Comment by amenity** [comment]
@dianamartin - is this ready to close?

**Comment by dianamartin** [comment]
Yes, I must’ve missed it
