### ISSUE TITLE
Feature: Have "311 Feedback" activity on (SR Details) 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#267]
**Page:** 
- [ ] Markings Service Request page
- [x] Service Request Details page
- [ ] Work Order/Job Details page
- [ ] Job Details page

**Comment by dianamartin** [comment]
This is configured. 

![image](https://user-images.githubusercontent.com/21112975/70456514-db3d2480-1a73-11ea-994c-a8be767757a6.png)

**Comment by johnclary** [comment]
yayyy!
