### ISSUE TITLE
Feature: Add Flex Notes table (Job Details)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#279]
**Page:** 
- [ ] Markings Service Request page
- [ ] Service Request Details page
- [ ] Work Order/Job Details page
- [x] Job Details page

### I want to be able to see the 311 SR Flex Notes easily 
![image](https://user-images.githubusercontent.com/21112975/69441145-c3de0780-0d0f-11ea-8fc7-1e4107f63f87.png)

**Comment by dianamartin** [comment]
I've attempted to do this on the Jobs details page and can't get it done, I think it's too far removed from the `csr issues`/`csr flex notes` object. 

I was able to get a button on the Markings Work Order details page, but that's it.

**Comment by dianamartin** [comment]
@johnclary this is a blocker, not sure if this is going to be possible.

**Comment by johnclary** [comment]
Blocked by #287 (see dependency).

**Comment by dianamartin** [comment]
Added the Flex notes table to the job details page.

**Comment by dianamartin** [comment]
Was going to run this by Christina before implementing in Prod. If she wants existing Flex Note order, or if we want to customize the order.

Need to set up `Sort Order Markings` with the following conditional rules

- [x] contains (Cross St) FLXQ0434 - 1
- [x] contains PROBLEM - 2
- [x] contains TYPEMARK - 3
- [x] contains TYPELONLI - 4
- [x] contains TYPECROS - 5
- [x] contains TYPESCHMA - 6 
- [x] contains TYPELEGE - 7
- [x] contains PRDEMTNM - 8
- [x] contains ANYTABRO - 9
- [x] contains ARYRNOMM - 10
- [x] contains SRSLADAT - 11
- [x] contains SRATTACH - 12
