### ISSUE TITLE
Ensure 311 activity rules for Markings don't impact the 311 system

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#280]
**Page:** 
- [ ] Markings Service Request page
- [X] Service Request Details page
- [ ] Work Order/Job Details page
- [ ] Job Details page

### Notes
Before adding activities records, make record rule send message to do not send.

**Comment by dianamartin** [comment]
Form: https://builder.knack.com/atd/signs-markings#pages/scene_1264/views/view_3152

Record Rules: 

Action - UPDATE THIS RECORD
When - Default
Values 
- `CSR ACTIVITY DATE` - current date
- `CREATED BY` - to logged in Account
- `PROCESS STATE ESB` - to custom - `DO NOT SEND`

**Comment by dianamartin** [comment]
Removed `PROCESS STATE ESB` rule because default is `READY TO SEND`.
