### ISSUE TITLE
Delete "csr_flex_notes" from Signs and Markings - Dec 2019

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-knack-signs-markings#281]

**Comment by SurbhiBakshi** [comment]
Received automated reminder to delete flex notes in Data Tracker PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
ISSUE_STATUS_CODE contains closed
CREATED_DATE is before 10/01/19

Total Records: 25,922
To Delete: 5,579 (number of records from running the query)
New Total: 20,343

Run Batch Delete
Same query
Filter:
ISSUE_STATUS_CODE contains closed
CREATED_DATE is before 10/01/19

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d270e6f8-3b28-4263-9780-865814812cc3)

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/3a8c6b59-09f3-4162-b3b9-50852bd5d292)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/82c9a061-c209-4ff5-96d9-b3faf5968de6)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1da1c054-12da-4f86-9ce0-9dde4fb82070)

**Comment by SurbhiBakshi** [comment]
2nd attempt started at 11:10 am
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6446df23-81a5-4fd5-9038-b77c12147789)

**Comment by SurbhiBakshi** [comment]
@johnclary , still can't do a batch delete process that takes care of all records to be deleted (5,579) at once. Also, the process takes way longer than Data Tracker, although I had to delete more records in Data Tracker. 



![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/bd69e55c-faf6-4e2d-8cc0-de197a17b02f)

**Comment by johnclary** [comment]
that's troubling. would you open a knack issue? i see this as related to our performance issue.

**Comment by SurbhiBakshi** [comment]
@johnclary will open a Knack issue

**Comment by SurbhiBakshi** [comment]
@johnclary Submitted Knack issue

**Comment by SurbhiBakshi** [comment]
Created an issue to follow the bug resolution by Knack. [#298] (https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-knack-signs-markings/298)
