### ISSUE TITLE
[Python] Connect Work Orders to Flex Notes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#287]
In order to meet #279, we need to connect markings work orders to their connected SR's flex notes.

Todo:
- [x] Add one-to-many connection field on `csr_flex_notes` to `work_orders_markings` (`field_3629`)
- [x] Add `COUNT_FLEX_NOTES` field to markings_work orders (`field_3632`)
- [x] Create Knack API view of markings flex notes (`scene_1271`, `view_3169`)
- [x] Create Knack API view of markings_work_orders that have an SR but no flex notes (`scene_1271`, `view_3170`)
- [x] Write script that fetches unattached SR flex notes, fetches related work order, and updates the flex note record connection  
- [ ] text with more records
- [ ] update deployment config / deploy

*Migrated to [atd-data-tech #1795](https://github.com/cityofaustin/atd-data-tech/issues/1795)*

**Comment by johnclary** [comment]
@dianamartin i ran the script and have flex notes connected to work order `MRK19-009590`. You should be able to build your flex notes table on the job details now. You add a table that shows "records connected to the parent work order" > "csr_flex_notes" (or something like that).

**Comment by dianamartin** [comment]
@johnclary Tried looking at this. Did you configure this on test or prod? I unfortunately can't see a related table for "csr_flex_notes".

**Comment by johnclary** [comment]
@dianamartin i ran the script once in prod. When you're adding the table you can find the choice under "Records further connected to this page's work_orders_markings_job". Screenshot attached.

<img width="750" alt="Screen Shot 2019-12-10 at 6 42 29 PM" src="https://user-images.githubusercontent.com/14793120/70581473-e92a9c80-1b7c-11ea-8038-789d898517d6.png">

**Comment by johnclary** [comment]
I can run the script again in test or prod if you create more work orders from SRs.

**Comment by dianamartin** [comment]
@johnclary thanks! I was only looking at it on Test that’s probably why.

**Comment by dianamartin** [comment]
@johnclary Confirmed I was able to see the flex note connection on the jobs page in Signs & Marking Prod. Wasn't able to configure the Test environment bc it doesn't exist there that I saw.

**Comment by dianamartin** [comment]
@johnclary I have 3 work orders in PROD now, if you wanted to run the script in PROD again.

**Comment by johnclary** [comment]
Ended up deploying this through the `atd-knack-api`: https://github.com/cityofaustin/atd-knack-api/pull/5

Which also required a change to the Knack custom js:
https://github.com/cityofaustin/atd-knack-signs-markings/pull/308

**Comment by johnclary** [comment]
will finalize testing with @dianamartin on Monday.
