### ISSUE TITLE
Signs and Markings Bug for batch delete process

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-knack-signs-markings#298]
Sent in a ticket to Knack
Dec 10, 5:04 PM EST 
Bug Location: Builder
URL: https://builder.knack.com/atd/signs-markings#data/object_172/records
Description: 
I am trying to run a batch delete process for the records in this object, I needed to delete around 5,500 records. But when I run the batch delete process, even though I get confirmation the batch will delete 5,579 total records, only 1,400 records got deleted the first time. I ran it again, and this time, only 1,149 records got deleted.
Permission to Manuplate Data: NOT Granted

**Comment by SurbhiBakshi** [comment]
@johnclary 

reply from Knack below - 


Sarto (Knack) 
Dec 10, 5:26 PM EST 
Hi Surbhi, 

Thanks for reaching out! This issue is actively being worked on by our developers, and I have linked to the bug here so we can notify you when it is resolved.

This is the ticket we'll be using going forward, to communicate further updates on the issue with Batch Delete not deleting all selected records.

Once this is resolved, we'll update you via this ticket, right away. Please do not hesitate to reach out with any other questions you may have, in the meantime!
Sarto at Knack
Helpdesk | Community | Developer Documentation | Status Page
Knack.com | Twitter | Facebook

**Comment by SurbhiBakshi** [comment]
Haven't heard back from Knack.

**Comment by SurbhiBakshi** [comment]
emailed Knack to check on status of issue.

**Comment by SurbhiBakshi** [comment]
Also waiting to hear back from Knack on [#1121](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/1121)

**Comment by SurbhiBakshi** [comment]
@dianamartin - safe to close this issue based on your experience, right?

**Comment by dianamartin** [comment]
@SurbhiBakshi Yes, based on the fact I could delete more than 1,000 records at a time. I think this is resolved.
