### ISSUE TITLE
Sprint Review: Markings 311 Module

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#302]
Attendees: Kati, Christina, Diana, Amenity
[Notes](https://docs.google.com/document/d/1aa8sUN3grQvOH9nEbGknizPDqpO6Em7BWBWKKmfuMjU/edit)

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Things to Change
### SR Markings table
- [ ] GIS QA filter will be GIS status field, yes/no - wants to see “Ready for QA - everything in Alan’s backlog
- [ ] Implement on Signs 
- [ ] Implement on Markings

### SR Details
- [ ] Hide “Work Groups” check boxes if there’s already a work order

### Work Order Details
- [ ] Hide 311 CSR # 
- [ ] Rename `Closed Date`

### Job Details page
- [ ] Flex Notes table - remove link to Jobs Details

**Comment by dianamartin** [comment]
Created issue [1053: Sprint Review - 311 Markings SR: Action Items](https://github.com/cityofaustin/atd-data-tech/issues/1053)
