### ISSUE TITLE
Add a "Priority" field to Signs and Markings Operations application

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-signs-markings#310]
For the Signs and Markings Operations application, we would like to add a `PRIORITY` field that can only be updated by the "Signs and Markings Supervisor" roles. This is because the need has come up to identify projects more clearly that are considered high priority.

This field should only be editable by Supervisors. 

Currently, priorities are discussed verbally and via email, but it's not clear to everyone.

They would like the priority field as soon as possible. They are going to be building a work calendar and would like to use the priorities for the work calendar. 

---
(Comes from) request ID: DTS20-100395
Requested by Christina T.

**Comment by dianamartin** [comment]
Checked in with Christina to see what the Markings supervisors would like to see in the `Priority` field. 1-4, have 3 as the default priority?

**Comment by dianamartin** [comment]
Talked to Christina and agreed on the choices: 
- Standard
- High
- Urgent

Added a form on the edit form for supervisors only
