### ISSUE TITLE
Reorganize layout of the map in relation to knack location fields

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-knack-signs-markings#34]
- [ ] Once we've removed the lat/lon fields from displaying inside the React iframe map, we need to make the default Knack lat/lon fields work better with the layout of the map.

- [x] We also need to bump down tile selector a hair not to overlap with the search field.

**Comment by mddilley** [comment]
CSS style changes to make the default Knack lat/lon fields/buton work better with the layout of the map are addressed in issue #51
