### ISSUE TITLE
Clean up Mapbox API tokens

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-knack-signs-markings#35]

**Comment by mateoclarke** [comment]
We should do a couple things to secure our mapbox API tokens once we switch to prod

- [ ] get a fresh token
- [ ] add URL restrictions for production and staging sites
- [ ] obscure tokens/use dotenv to inject them as environment variables.
- [ ] more?

**Comment by mddilley** [comment]
URL restrictions covered by new issue #39
