### ISSUE TITLE
Delete Signs specific rules in Markings Work Orders

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#53]
Ex. 
- [x] delete display rules on former Signs & Markings work order
- [x] display rules on Attachment form
- [x] other forms that apply

**Comment by dianamartin** [comment]
@johnclary here is the issue about deleting rules and Signs specific stuff on the markings work orders.

**Comment by johnclary** [comment]
done, as far as i can tell:
- change signs and markings work types to default to each respective work type
- remove dig tess number, regulation from new markings work order form
- remove regulation attachment check from conditional rules of hold_plans
- remove reg related rules from work order status and hold status
- delete regulation field from markings
- delete sum_regulation field from markigns
- remove "signs" from workgroup selector
- remove signs related display-rule form work order details
