### ISSUE TITLE
Create Signs Work Orders GIS Feature Classes

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#63]
We need to create new feature classes for signs work orders.

- [x] Work Orders
- [x] Locations
- [x] Assets

One work order >> relates to many locations >> relates to many assets

**Comment by amenity** [comment]
@jaime-mckeown - hopefully we can do this during Sprint 4 pretty quickly after #66.

**Comment by dianamartin** [comment]
@alan-deanda Seems like you're missing the required related tables we were needing:

- `work_orders_signs_tbl`
- `attachments_tbl`
- `materials_tbl

I emailed Susanne to see if she has her old pavement markings .mxd she can share with us.
`

**Comment by dianamartin** [comment]
Susanne's reply
>The file path to the MXD I used to create the Pavement Markings Work Orders is located here: 
**G:\ATD\ATD_GIS\Markings\Road_Markings_Work_Orders_Web_Map**


>The file path to the file geodatabase used to create the relationships is here:
**G:\ATD\ATD_GIS\Markings\map_data\ATD_Signs_Markings.gdb**

I believe the relationships to the table must be in the same file geodatabase as the signs feature classes.

**Comment by alan-deanda** [comment]
@dianamartin  thanks, I will add the tables and update this issue once that is done.

**Comment by alan-deanda** [comment]
@dianamartin the 3 tables have been created. Currently they're sitting in ATD_GIS\DATA_COLLECTION\Signs_Digitizing_Assets\signs_work_orders.gdb , but I think I may need some help understanding the relationships to the other datasets before uploading to AGOL

**Comment by alan-deanda** [comment]
@johnclary  @dianamartin  I've published Signs_Work_Orders_AGOL to AGOL (SM folder)

**Comment by johnclary** [comment]
@alan-deanda minor issue: the CREATED_BY and MODIFIED_BY field names on the `sign_specification_actuals` layer are too short—only 8 characters. I would suggest updating to 50. 

No need to fix now because I will probably have additional changes once I keep working through the layers. Will keep you posted.

cc @dianamartin

**Comment by johnclary** [comment]
Just keeping a running list of issues here. @alan-deanda i'm ready for you to make these changes to `sign_specification_actuals`. I haven't tested relationships yet, so there may be more.

#### Misc / All
- [x] Add Human-Friendly Field Aliases (talk to Diana if unsure)

#### [`sign_specification_actuals`](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Signs_Work_Orders_AGOL/FeatureServer/0?token=Z-Cgo_YHwEppk9cBpQWHydrD-Z7mxDm8FwLzWuQBKbwnrRzTAsSQ4AnI0IXYbt-Mf_0HSMKiihPT8L_geKdUn62ehE7KWa4RfQoQ-9qRcwSxbcaNqzhfOyCthgNm_O7QfOeekyOZ9f7ziNnKpoeMrdCqx7jVgXAWv33ScaBId8bkllrjY-tRWGI_l2g21kAePGThQkcQXYwTty0WP4oGsnH-GkynDoSFGnNiY9kOJpdo7LNFzBPV_fSAeFE9UHpK)

- [x] CREATED_BY, MODIFIED_BY: increase field length to 50 characters
- [x] There are duplicate CREATED_BY and MODIFIED_BY fields. Need to be removed. Doesn't matter which are removed.
- [x] Need to add a file attachment field with name PHOTO.
- [x] Remove `Signs_Location_Latitude` and `Signs_Location_Longitude` fields. (These are sent to the geometry object which is not exposed in the table)

#### [`work_orders_signs`](https://services.arcgis.com/0L95CJ0VTaxqcmED/ArcGIS/rest/services/Signs_Work_Orders_AGOL/FeatureServer/3)
- [x] I'd like to change this from a table to a multipoint feature class. I think it will be useful to have the multipoint sign locations on this layer. So you can easily see all work locations on a single work order. I think @dianamartin initially suggested it, and now I agree :)
- [x] `CREATED_DATE` is small integer—change to date type.

**Comment by alan-deanda** [comment]
@johnclary  I've updated the [feature service in AGOL](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Signs_Work_Orders_AGOL/FeatureServer) according to the above specs. Let me know if anything else needs to change and I'll make the updates

**Comment by johnclary** [comment]
thanks @alan-deanda. we need this to be **multipoint**, not single point. Would you fix and republish? While you're at it, would you set `DIG_TESS_NUMBER` to be a string, not integer?

**Comment by alan-deanda** [comment]
@johnclary d'oh! yes, I'll republish. By the way, is there a less robotic way of writing DIG TESS NUMBER? is TESS an accronym? Any thoughts, @dianamartin ?

**Comment by dianamartin** [comment]
@alan-deanda DIG Tess is how the users refer to it. I don't believe it is an acronym
https://www.texas811.org/digtess

**Comment by alan-deanda** [comment]
@johnclary work_order_signs has been republished as multipoint and the DIG_TESS_NUMBER field is now a string.

**Comment by johnclary** [comment]
@alan-deanda the feature classes looks good, but there's something odd going on with the relationships. it appears that the relationships have been triplicated. didn't know that was possible. can you verify that the GDB you're publishing from only has one set of relationships? we may have to delete the AGOL service and publish as new.![Screen Shot 2019-10-11 at 9.47.11 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/1ebd24af-0c68-455b-8c44-d9c40866f74d)

**Comment by alan-deanda** [comment]
@johnclary  I've re-published the feature service and removed the extra relationships

**Comment by johnclary** [comment]
we're good to go! @alan-deanda thanks for you help on this.

**Comment by johnclary** [comment]
@alan-deanda last task for this: would you please update metadata and dataset description?

**Comment by alan-deanda** [comment]
@johnclary the metadata and description have been updated.
