### ISSUE TITLE
Signs GIS Asset Management

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#64]

**Comment by alan-deanda** [comment]
@johnclary , do you mind if I use this issue to track my progress on the signs asset tracking?

**Comment by johnclary** [comment]
@alan-deanda yes please

**Comment by alan-deanda** [comment]
- [~] Testing versioning
- [~] Testing attribute assistant in MXD - generating IDs after version edits are compiled and posted to DEFAULT
- [x] Using Susanne's mxd to set up relationships between tables

**Comment by alan-deanda** [comment]
Signs Feature Service has been re-published to AGOL to meet specs and will be tested soon.

**Comment by johnclary** [comment]
Pending migration of Markings QA/QC process to ArcGIS Pro.
