### ISSUE TITLE
Overlay "Submit" Button On Map

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#72]
On smaller screens the Knack form submit button may not be visible when using the map; the user has to scroll down to click "submit". It would be ideal to have the submit button overlayed on the map so that the user can quickly submit a location they want to create/edit. This applies to the add location/edit location pages.

Once complication is that the submission form should be hidden under certain conditions, e.g., the work order is closed. We are currently addressing this in the Knack app with page rules.

**Comment by mateoclarke** [comment]
This is basically the same issue as #51

**Comment by mddilley** [comment]
This issue is closed upon merge of #51.

**Comment by mddilley** [comment]
#51 closed and merged. Closing this issue.
