### ISSUE TITLE
Issues Punch List 7/9

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#89]
**FROM TECHNICIAN NOTES**
- [x] 1. FEATURE: Rebuild My Work Order on new My Work Orders page (to set Technician role to only see that) what about Markings technicians?
>rebuilt **My Work Orders for Non Technicians** and **My Work Orders for Assigned To (Technicians)**
Added all Display rules for `Status` field

- [x] 2. FEATURE: Technician to log into My Work Order page - view tabs based on user roles
>Removed the other tabs on the Page menu so that Home and My Work Orders is visible

- [x] 3. FEATURE: New Work Order created by Technician, to go into ISSUED status initially
>Added record rules from SR -->WO creation
(Ex. Hold Plans = No, Hold Regulations = No, Hold Other = No, Hold Work Order = No, Issued = Yes, Work Order Status = Issued)
Tested this and it looks like it is working.

**FROM VIEWER NOTES**
- [ ] 4. FEATURE: Add Bike Field - work order signs object table
When Requester is Active Transportation and Street Design
This field to display on new work order form. 
Add to Edit form.

>This needs further discussion with Active Transportation. Kati will reach out to them and get back to me. We decided 7/10 that we won't worry about this until we figure out we can't get what we need from reporting.

- [x] 5. FEATURE: Create a NEW MENU for Viewer
HIDE: Issue, Submit for Review, Close WO, GIS)
>Found really weird issue when copying menu from Work Order Details to Signs Work Orders page. I think it copied all the button pages and it made an extra copy. I deleted those that weren't associated to a user role menu. 

- [ ] 6. BUG: Request for Cancellation Display Rules are not working as expected
Looked into this and is not functioning as designed. 
Need to rebuild REQUEST CANCELLATION form/page: https://builder.knack.com/atd/signs-markings#pages/scene_914
@johnclary can you take a look at this?
>Testing this morning and still being crappy. It appears when all display rules are removed. I rebuilt it yesterday. 

- [x] 7. BUG: Edit Form - Technician form 
Wasn't updating 
Weirdness is happening, it won't update the Edit technician form.
@johnclary can you take a look at this?
>This was from the extra button pages, I think I figured this out. We can actually remove the extra forms and lighten the page rules.

**FROM SUPERVISOR NOTES**
- [ ] 8. Work on GIS QA Process
Can't get to page from Closed 

- [ ] 9. ReOpen button
Currently on Closed Status, Kati thinks it needs to be on Final Review page. 

- [ ] 10. Supervisor kicks back the WO for the technician to do something. In markings scenario, we could create another job. In signs, the work order is in Final Review. 
We need to make it go back to Issued.

**Comment by johnclary** [comment]
@dianamartin the issue is that the "attachment status" and "request cancellation" columns are not displaying, right? this looks like a bug, and the table would need to be rebuilt.

however, looking at the markings work orders, they do not have an not-editable and editable attachments table. do we even need the two tables?

**Comment by johnclary** [comment]
@dianamartin can you clarify which form you're referring to with "Technician form"?

**Comment by dianamartin** [comment]
@johnclary It was the edit form for technicians, there are several form versions for particular user roles.

**Comment by dianamartin** [comment]
Closing issue, created separate issues for the outstanding tasks.
