### ISSUE TITLE
Email Notifications for Migration URL change

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-signs-markings#94]
- [x] Email "Data Tracker | Requesters" on change of URL and process **(Emailed on 7/11)**
>WHAT'S HAPPENING – Thursday, July 25th at 8:00 am – Friday, July 26th at 5:00 pm 
Process for entering a Signs work order is changing and the Signs & Markings Work Order module URL is changing.
 
>WHY ARE WE DOING THIS?
The existing application configuration was difficult maintain with incoming enhancement configurations for Signs work tickets, so to streamline development we changed a few things including the page URL. 

>WHAT IS IMPACTED?
The following application: Data Tracker: Signs & Markings work orders 
If you will not be able to enter any new work orders, comment or attachments during this time period.  

>WHAT IS REQUIRED OF YOU?
You will need to update any bookmarks you have for the existing Signs & Marking work order page to the new one. You will be given the new URL in the upcoming email notifications. 

>HOW TO GET TECHNICAL SUPPORT?
If you have questions please email transportation.data@austintexas.gov if you experience any issues after the maintenance work is completed.

>Please forward this notice on to anyone that may benefit knowing this information.

- [x] Email 2 day reminder to "Data Tracker | Requesters" about What's Happening **(Emailed on Tuesday, 7/23 @ 11:44 am)**
>WHAT'S HAPPENING – Thursday, July 25th at 8:00 am – Friday, July 26th at 5:00 pm 
Process for entering a Signs work order is changing and the Signs & Markings Work Order module URL is changing.
 
>WHY ARE WE DOING THIS?
The existing application configuration was too difficult maintain with incoming enhancement configurations for Signs work tickets, so to streamline development we changed the page URL. We will also be migrating the Signs data into this

>WHAT IS IMPACTED?
The following application: Data Tracker: Signs & Markings work orders 
You will not be able to enter any new work orders, edit work orders, make comments or attachments during this time period.  

>WHAT IS REQUIRED OF YOU?
You will need to update any bookmarks you have for the existing Signs & Marking work order page to the new one.

>UPDATE YOUR BOOKMARKS 
You will receive the new site URL once maintenance is complete.

>HOW TO GET TECHNICAL SUPPORT?
Please email transportation.data@austintexas.gov if you have any questions or experience any issues after the maintenance work is completed.

>Please forward this notice on to anyone that may benefit knowing this information.

- [x] Email "Start of Maintenance" **(Emailed on Wednesday, 7/25/19 @ 9:37 am)**
>WHAT'S HAPPENING – Thursday, July 25th at 8:00 am – Friday, July 26th at 5:00 pm 
Process for entering a Signs work order is changing and the Signs & Markings Work Order module URL is changing.
 
>WHY ARE WE DOING THIS?
The existing application configuration was difficult maintain with incoming enhancement configurations for Signs work tickets, so to streamline development we changed the page URL. 

>WHAT IS IMPACTED?
The following application: Data Tracker: Signs & Markings work orders 
If you will not be able to enter any new work orders, comment or attachments during this time period.  

>WHAT IS REQUIRED OF YOU?
You will need to update any bookmarks you have for the existing Signs & Marking work order page to the new one.

>UPDATE YOUR BOOKMARKS 
You will receive the new site URL once maintenance is complete.

>HOW TO GET TECHNICAL SUPPORT?
Please email transportation.data@austintexas.gov if you have any questions or experience any issues after the maintenance work is completed.

- [x] Email "End of Maintenance"

**Comment by dianamartin** [comment]
Made email notification drafts 
- [ ] Need to export user list in data tracker

**Comment by johnclary** [comment]
Sent. Thanks, @dianamartin!
